    - name: Check if pm2 is installed
      command: "which pm2"
      register: pm2ExistCode

    - name: Installing pm2
      npm:
        name: pm2
        global: yes
        state: present
      when: pm2ExistCode.rc != 0